### ISSUE TITLE
Setting f1 as metrics but get acc during training and evaluating

### ISSUE THREAD

**Issue by linpeisensh** [manujosephv/pytorch_tabular#100]
**Describe the bug**
I set config as following:
```
trainer_config = TrainerConfig(
    auto_lr_find=True, # Runs the LRFinder to automatically derive a learning rate
    batch_size=1024,
    max_epochs=100,
    gpus=0, #index of the GPU to use. 0, means CPU
    auto_select_gpus=False,
    checkpoints = "valid_f1",
    checkpoints_path = './',
    checkpoints_mode = 'max',
    checkpoints_save_top_k = 3
)
optimizer_config = OptimizerConfig()

model_config = NodeConfig(
    task="classification",
    num_layers=2,
    metrics=["f1"]
)
```

But I get acc as f1 during training and evaluating.
![image](https://user-images.githubusercontent.com/52672986/200764753-804a6eaa-2e1f-42c5-ae0b-9d1bb4ec6369.png)

**Expected behavior**'
Could you tell me how to set config to solve this problem.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
Thank you in advance! @manujosephv

**Comment by linpeisensh** [comment]
Then I set config as doc:
https://pytorch-tabular.readthedocs.io/en/latest/tutorials/06-Imbalanced%20Classification/
```
model_config = NodeConfig(
    task="classification",
    metrics=["f1","accuracy"], 
    metrics_params=[{"num_classes":2},{}]
)
```
Then the following is printed during training:
Epoch 0:   5%|▌         | 28/510 [16:16<-2:09:34, -0.07it/s, loss=0.351, valid_loss=0.693, valid_f1=0.756, valid_accuracy=0.756, train_loss=0.330, train_f1=0.862, train_accuracy=0.862]

f1 is the same as accuracy.

**Comment by manujosephv** [comment]
Can you check-out the latest main branch and install from it and re-check the issue? That would help me isolate the issue much faster.
`pip install git+https://github.com/manujosephv/pytorch_tabular.git`

**Comment by linpeisensh** [comment]
![image](https://user-images.githubusercontent.com/52672986/201275421-fd48d52a-bcc6-4d75-9977-840b283d62d1.png)
I have reinstalled as pip install git+https://github.com/manujosephv/pytorch_tabular.git. Howerver, the f1 is still the same as accuracy as this figure shows.

**Comment by manujosephv** [comment]
I double checked the implementation and there is no bug in the code. But in certain situations, f1 score and accuracy can be the same. Check [this](https://datascience.stackexchange.com/a/64696) stackoverflow discussion for details.
