### ISSUE TITLE
Support for MPS as accelerator

### ISSUE THREAD

**Issue by Aceticia** [manujosephv/pytorch_tabular#102]
**Is your feature request related to a problem? Please describe.**
I prototype networks on my apple M1 laptop and it looks like pytorch and pytorch lightning already support it. I'd like to use it to speed up my work.

**Describe the solution you'd like**
In `config.py` we need to change the interface a bit, and in `tabular_model.py` [line 331](https://github.com/manujosephv/pytorch_tabular/blob/5ea29cbe97009cc157e9332be931273af874d297/pytorch_tabular/tabular_model.py#L331) we should get away with not changing anything.

**Describe alternatives you've considered**
Not using mps is meh

**Comment by manujosephv** [comment]
@Aceticia I'm currently working on a major update to PyTorch Tabular and in that I have made provisions to include any parameter that PyTorchLightning supports. I hope that should address this shortcoming

**Comment by manujosephv** [comment]
@Aceticia Just released a new version, 1.0.0 and with it `accelerator` is a parameter in `TrainerConfig`. Let me know if this is working for you and reopen if it doesn't
