### ISSUE TITLE
Problem with model saved with "salve_model_for_inference"

### ISSUE THREAD

**Issue by micheleFraccaroli** [manujosephv/pytorch_tabular#105]
I have succesfully trained a FTTransformer. Now I want save the model in pytorch format and use the model for making inference on new data.

This is the code:

```
csv_path = "C:/Users/path/to/dataset.csv"
df = pd.read_csv(csv_path, sep=";")
df.drop("Class", axis=1, inplace=True)
features = list(df.columns)

train, test = model_selection.train_test_split(df, test_size=0.2, shuffle=True)
train, val = model_selection.train_test_split(train, test_size=0.2, shuffle=True)

model = torch.load("path/inference/model.pt") #model saved with "save_model_for_inference"

model.eval()

with torch.no_grad():
    res = model(test)

print(res)

```

But I'have the error:

> Traceback (most recent call last):
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\pandas\core\indexes\base.py", line 3803, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'continuous'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\mfraccaroli\Desktop\UniLrn_vs_pytorch\inference.py", line 38, in <module>
>     res = model(test)
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\pytorch_tabular-0.7.0-py3.10.egg\pytorch_tabular\models\base_model.py", line 224, in forward
>     x = self.compute_backbone(x)
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\pytorch_tabular-0.7.0-py3.10.egg\pytorch_tabular\models\base_model.py", line 191, in compute_backbone
>     x = self.backbone(x)
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\pytorch_tabular-0.7.0-py3.10.egg\pytorch_tabular\models\ft_transformer\ft_transformer.py", line 164, in forward
>     continuous_data, categorical_data = x["continuous"], x["categorical"]
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\pandas\core\frame.py", line 3805, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "C:\Users\mfraccaroli\Miniconda3\envs\nvidia_pytorch\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
>     raise KeyError(key) from err
> KeyError: 'continuous'

This is the code that I have written for train the model:

```
from pytorch_tabular import TabularModel
from pytorch_tabular.models import FTTransformerModel, FTTransformerConfig
from pytorch_tabular.config import DataConfig, OptimizerConfig, TrainerConfig, ExperimentConfig
import pandas as pd
from sklearn import model_selection
from torchmetrics import Accuracy, AUROC, PrecisionRecallCurve, Precision, Recall
from pytorch_tabular.utils import get_balanced_sampler, get_class_weighted_cross_entropy
import torch

def Normalize(df):
    means, stds = {}, {}
    for n in df.columns:
        means[n], stds[n] = df[n].mean(), df[n].std()
        df[n] = (df[n]-means[n]) / (1e-7 + stds[n])
    return df

csv_path = "C:/path/to/dataset.csv"
df = pd.read_csv(csv_path, sep=";")
df.drop("Unnamed: 43", axis=1, inplace=True)
features = list(df.columns)

train, test = model_selection.train_test_split(df, test_size=0.2, shuffle=True)
train, val = model_selection.train_test_split(train, test_size=0.2, shuffle=True)

data_config = DataConfig(
    target=['Class'], #target should always be a list. Multi-targets are only supported for regression. Multi-Task Classification is not implemented
    continuous_cols=features,
)

trainer_config = TrainerConfig(
    auto_lr_find=True, # Runs the LRFinder to automatically derive a learning rate
    batch_size=128,
    max_epochs=100,
    gpus=1, #index of the GPU to use. 0, means CPU
)
optimizer_config = OptimizerConfig()

model_config = FTTransformerConfig(
    task="classification",
    learning_rate = 1e-3,
    metrics=["auroc", "accuracy", "precision", "recall"],
    metrics_params=[{"num_classes": 2}, {}, {}, {}],
    attn_feature_importance=True,
)

exp_config = ExperimentConfig(
    project_name="Unbalanced_Classification",
    run_name="FT-Transformer",
    log_target="tensorboard",
)

tabular_model = TabularModel(
    data_config=data_config,
    model_config=model_config,
    optimizer_config=optimizer_config,
    trainer_config=trainer_config,
    experiment_config=exp_config,
)

tabular_model.fit(train=train, validation=val)
result = tabular_model.evaluate(test)
pred_df = tabular_model.predict(test)
pred_df.to_excel("pred_result.xlsx")
tabular_model.save_model("examples/basic")

tabular_model.save_model_for_inference("path/inference/model.pt", kind="pytorch")
```

Any idea how to fix?

**Comment by manujosephv** [comment]
`save_model_for_inference` saves the trained model as a pure pytorch model. So, the input expected by the model is not a dataframe anymore, but a dictionary of categorical and continuous tensors (that is what comes out of the dataloader it was trained with).

you will have to use the `datamodule` that you trained with (you can find it as `tabular_model.datamodule`) and use the `prepare_inference_dataloader` method which takes as an input the dataframe.

You can refer the [predict](https://github.com/manujosephv/pytorch_tabular/blob/a510b23b8f49c6e63f0a644ac7a8b99c1f7d910b/pytorch_tabular/tabular_model.py#L1027) method in TabularModel to get an idea of how to do inferencing.

**Comment by manujosephv** [comment]
closing this. If you have any questions, feel free to reopen
