### ISSUE TITLE
Remove non-graphical output from docs

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#11]
The probabilistic regression example in the docs shows reams of floating point numbers as output, rather than some sort of graphic, which is not very useful:

https://pytorch-tabular.readthedocs.io/en/latest/tutorials/07-Probabilistic%20Regression%20with%20MDN/

The figure that is supposed to be output in the last cell, however, is not shown. 

![Screenshot 2021-05-03 1 12 59 PM](https://user-images.githubusercontent.com/81476/116915176-4f500d80-ac11-11eb-90ee-24870076e7d3.png)

**Comment by manujosephv** [comment]
Just saw that! I'll see what I can do. The plotly plots are not playing nice with the documentation.

**Comment by manujosephv** [comment]
I've rendered all the plotly plots as images and linked to the notebook/tutorial. Have updated in the develop branch and will push it to the main and subsequently to readthedocs soon..

**Comment by manujosephv** [comment]
Fixed now.
