### ISSUE TITLE
[New Feature] Hyperparameter tuning

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#12]
I did not see a discussion forum anywhere, so please excuse a question in the issue tracker.

I noticed Optuna integration on the project roadmap. Are any of the other tuning packages (e.g. Ray) currently compatible with PyTorch Tabular?

**Comment by manujosephv** [comment]
No problem.. the project is still pretty new.. so no discussion board yet.

And currently it doesn't support any  hyperparameter tuning out of the box. You will have to write some code to implemented hyperparameter tuning.

Wanted to integrate at least one hyperparameter tuning framework and hence put the Optuna integration on the roadmap. Just haven't gotten enough time to actually do it yet.

**Comment by fonnesbeck** [comment]
Great to hear. Its been a valuable tool for my research so far, so thanks.
