### ISSUE TITLE
Examples? Empirical validation?

### ISSUE THREAD

**Issue by mgreenbe** [manujosephv/pytorch_tabular#14]
I'm really enjoying working with `pytorch_tabular`, but I've only done some toy computations with small datasets. Can you recommend any (tabular) datasets that show off the usability and utility of `pytorch_tabular`? I'm interested, specifically, in ones where results are competitive with XGBoost and similar non-deep-learning approaches. If you can point me in a fruitful direction, I'll work through some computations and happily open some PRs to add tutorials to the docs.

**Comment by mgreenbe** [comment]
Ok! I'll check them out and be in touch...

**Comment by manujosephv** [comment]
@mgreenbe Just checking back in. Did you manage to make some progress on this?
