### ISSUE TITLE
Binary classification metrics throws error in v 1.0.0

### ISSUE THREAD

**Issue by manujosephv** [manujosephv/pytorch_tabular#148]
**Describe the bug**
Binary Classification task with default settings throws an error in metric calculation.

**To Reproduce**
```python
data_config = DataConfig(
    target=['target'], #target should always be a list. Multi-targets are only supported for regression. Multi-Task Classification is not implemented
    continuous_cols=num_col_names,
    categorical_cols=cat_col_names,
)
trainer_config = TrainerConfig(
    auto_lr_find=True, # Runs the LRFinder to automatically derive a learning rate
    batch_size=1024,
    max_epochs=100,
    accelerator="auto", # can be 'cpu','gpu', 'tpu', or 'ipu' 
)

model_config = CategoryEmbeddingModelConfig(
    task="classification",
    layers="32-16", # Number of nodes in each layer
    activation="LeakyReLU", # Activation between each layers
    dropout=0.1,
    initialization="kaiming",
    learning_rate = 1e-3
)


tabular_model = TabularModel(
    data_config=data_config,
    model_config=model_config,
    optimizer_config=optimizer_config,
    trainer_config=trainer_config,
)
tabular_model.fit(train=train, validation=val)
```
will throw below error:
```
RuntimeError: Predictions and targets are expected to have the same shape, but got torch.Size([419, 2]) and torch.Size([419]).
```

**Expected behavior**
It should train with default Accuracy metric

**Additional context**
pytorch_tabular version 1.0.0

**Comment by manujosephv** [comment]
Known bug and will be fixed in next release.

**Workaround:**

Define metrics explicitly, like below:
```python
model_config = CategoryEmbeddingModelConfig(
    task="classification",
    layers="32-16", # Number of nodes in each layer
    activation="LeakyReLU", # Activation between each layers
    dropout=0.1,
    initialization="kaiming",
    learning_rate = 1e-3,
    metrics=['accuracy', "f1_score"],
    metrics_params=[dict(task="multiclass", num_classes=2), dict(task="multiclass", num_classes=2)]
)
```

**Comment by manujosephv** [comment]
This is not fixed in v1.0.1 in PyPi.

`pip install -U pytorch_tabular` to install new version

**Comment by destefani** [comment]
I run into a similar problem. I'm using the `CategoryEmbeddingModelConfig` to do binary classification and would like to get the F1 Score of the positive class. The problem with the workaround you suggest above is that it only works when averaging. Normally in `torchmetrics` you would use `binary_f1_score`, but because it is in `torchmetrics.functional.classification` instead of `tochmetrics.functional` it is not recognized.

**Comment by manujosephv** [comment]
`torchmetrics` have updated their interfaces a bit and created separate functions like `binary_f1_score`. `PyTorchTabular` hasn't been updated to use these new functions yet. But If I remember correctly, the legacy `f1_score` has a parameter called `task` with which you can define the desired averaging, isn't it?

**Comment by manujosephv** [comment]
It shouldn't be.. I'll unpin it . 👍🏽
