### ISSUE TITLE
issues with installation

### ISSUE THREAD

**Issue by SalvatoreRa** [manujosephv/pytorch_tabular#149]
**Describe the bug**
Not sure if it is only my issue or if it is a bug for the moment. I updated to the latest version which works fantastically (congratulations on all the work). However, to install I had some issues:

**To Reproduce**
this is not working:
`pip install pytorch_tabular[extra]`
or using this:
`pip install pytorch_tabular`

at least, when I tried to import this it gave me an error
`from pytorch_tabular.models.common.heads import LinearHeadConfig`

checking in the library in my anaconda folder I noticed that it was the previous version

I tried this without success:
```
git clone git://github.com/manujosephv/pytorch_tabular
pip install .

```
At the end what it worked: 

```
sudo git clone https://github.com/manujosephv/pytorch_tabular.git
cd pytorch_tabular
pip install .
```

I hope it can be helpful,
have a nice day and again compliments for your amazing work

**Desktop (please complete the following information):**

Linux Ubuntu
python 3.7

**Comment by manujosephv** [comment]
If you already have PyTorch TAbular installed, you need to use:
`pip install -U pytorch_tabular[extra]` to indicate that the library should be updated to new version.
