### ISSUE TITLE
Returns ValueError

### ISSUE THREAD

**Issue by rezamousavi** [manujosephv/pytorch_tabular#152]
I'm really enjoying using this package. It returned an AUC of almost one on a test data. However, when I want to apply it to a data set with no labels (e.g. Kaggle competition data), it returns:
ValueError: y contains previously unseen labels: [-3.2328808487512815]

code that results in error:
tabular_model.predict(kaggleTest)

To get around this, I added the label column to the kaggle data by using 0 for each value. The results were all very close to zero as if the labels were used to create the predictions. Can you please help?

**Comment by manujosephv** [comment]
Can you give more details? A reproducible example?

And from what I've seen from what you mentioned, double check if you have not added the target column as one of the features in the DataConfig..

**Comment by rezamousavi** [comment]
Thank you for getting back to me, Manu. I'm using your sample code in https://pytorch-tabular.readthedocs.io/en/latest/tutorials/01-Basic_Usage/. In train, test, and val objects in the tutorial, there is the target variable "target". However, I want to apply the trained and evaluated model to a new data for which I have all the same features as in train, test, and val but I do not have column "target". How do you go about applying the trained model to a new data without the target column? you help is much appreciated.

**Comment by rezamousavi** [comment]
Resolved the issue.
