### ISSUE TITLE
local variable 'x_cat' referenced before assignment

### ISSUE THREAD

**Issue by PSCM** [manujosephv/pytorch_tabular#160]
Hello. For some reason, every experiment I try to run fails, with the following message: **UnboundLocalError: local variable 'x_cat' referenced before assignment**

The entire message is accompanied by this code:

`UnboundLocalError                         Traceback (most recent call last)`
`[<ipython-input-106-cc57dae4e309>](https://localhost:8080/#) in <module>`
`----> 1 tabular_model.fit(train=X_train, test=X_test)`

`29 frames`
`[/usr/local/lib/python3.8/dist-packages/pytorch_tabular/models/tab_transformer/tab_transformer.py](https://localhost:8080/#) in forward(self, x)`
`    113         if self.hparams.categorical_dim > 0: `
`    114             x_cat = self.embed_input(dict(categorical=x["categorical"])) `
`--> 115         x = self.compute_backbone(dict(categorical=x_cat, continuous=x["continuous"]))`
`    116         return self.compute_head(x)`

My dataconfig is as follows:
`data_config = DataConfig(`
  `  target=['emotion'], `
    `continuous_cols=num_col_names,`
    `#categorical_cols=cat_col_names,`
    `#normalize_continuous_features=True`
)

My dataset consists only of continuous variables. All development is conducted on Google Colab

Note: when creating an experiment with the NODE model, with the same data and strategies, the result is correct.

**Comment by manujosephv** [comment]
That's a bug. I have pushed a fix to the main branch. Can you install directly from the branch and see if it works now?

As a side note, if there is no categorical features, `TabTransformer` is nothing but a feed forward network. The transformer part only works on the categorical features in `TabTransformer`. I'd suggest you to use FTTransformer or AutoInt, both of which uses the continuous features also in the transformer.

**Comment by PSCM** [comment]
It worked. Thank you very much!
