### ISSUE TITLE
'MPS' Accelerator to accomodate Apple Silicon?

### ISSUE THREAD

**Issue by jnacey2** [manujosephv/pytorch_tabular#163]
Is it possible to add the 'mps' as an option for an accelerator?  Pytorch Lightning has it implemented.

**Comment by manujosephv** [comment]
Are you using the latest version? It should support `accelerator="mps`

**Comment by jnacey2** [comment]
Yes, I'm using 1.0.1.  Here's the traceback from my configs...

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 14
      3 from pytorch_tabular.config import (
      4     DataConfig,
      5     OptimizerConfig,
      6     TrainerConfig,
      7 )
      9 data_config = DataConfig(
     10     target=["target"], 
     11     continuous_cols=[x for x in df.drop('target', axis=1).columns],
     12 )
---> 14 trainer_config = TrainerConfig(
     15     auto_lr_find=True,  # Runs the LRFinder to automatically derive a learning rate
     16     batch_size=64,
     17     max_epochs=1000,
     18     early_stopping_patience=10,
     19     accelerator='mps'
     20 )
     22 optimizer_config = OptimizerConfig()
     24 model_config = CategoryEmbeddingModelConfig(
     25     task="classification",
     26     layers="10000-5000-2500-1024-512",  # Number of nodes in each layer
     27     activation="LeakyReLU",  # Activation between each layers
     28     learning_rate=1e-3
     29 )

File <string>:39, in __init__(self, batch_size, data_aware_init_batch_size, fast_dev_run, max_epochs, min_epochs, max_time, gpus, accelerator, devices, devices_list, accumulate_grad_batches, auto_lr_find, auto_select_gpus, check_val_every_n_epoch, gradient_clip_val, overfit_batches, deterministic, profiler, early_stopping, early_stopping_min_delta, early_stopping_mode, early_stopping_patience, early_stopping_kwargs, checkpoints, checkpoints_path, checkpoints_every_n_epochs, checkpoints_name, checkpoints_mode, checkpoints_save_top_k, checkpoints_kwargs, load_best, track_grad_norm, progress_bar, precision, seed, trainer_kwargs)

File ~/opt/anaconda3/envs/dl/lib/python3.9/site-packages/pytorch_tabular/config/config.py:522, in TrainerConfig.__post_init__(self)
    521 def __post_init__(self):
--> 522     _validate_choices(self)
    523     if self.gpus is not None:
    524         warnings.warn(
    525             "The `gpus` argument is deprecated in favor of `accelerator` and will be removed in a future version of PyTorch Tabular. Please use `accelerator='gpu'` instead.",
    526             DeprecationWarning,
    527         )

File ~/opt/anaconda3/envs/dl/lib/python3.9/site-packages/pytorch_tabular/config/config.py:50, in _validate_choices(cls)
     48 if "choices" in atr.metadata.keys():
     49     if getattr(cls, key) not in atr.metadata.get("choices"):
---> 50         raise ValueError(
     51             f"{getattr(cls, key)} is not a valid choice for {key}. Please choose from on of the following: {atr.metadata['choices']}"
     52         )

ValueError: mps is not a valid choice for accelerator. Please choose from on of the following: ['cpu', 'gpu', 'tpu', 'ipu', 'auto']

**Comment by jnacey2** [comment]
Looking into this a bit more, I've added 'mps' as an option in the config.py file.  Apparently there is a fix in the works from pytorch_lightning (see here: https://github.com/Lightning-AI/lightning/pull/13992).  When working through this, for some reason my platform.processor() returns 'i386' instead of an arm architecture.  I'm on a new M2 Pro, btw, so think it must be an issue with this chip that needs to be worked out.

**Comment by manujosephv** [comment]
ah! that might be why "auto" doesn't work. And the config only supported some of the options mentioned [here](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#accelerator). But I see there are other options as well mentioned [here](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer-class-api). Can you raise a PR?
