### ISSUE TITLE
Memory Consumption is high

### ISSUE THREAD

**Issue by simpsus** [manujosephv/pytorch_tabular#165]
**Describe the bug**
The training fails during setup with the following message
`2023-02-18 12:36:04,883 - {pytorch_tabular.tabular_datamodule:286} - INFO - Setting up the datamodule for regression task

MemoryError: Unable to allocate 28.6 GiB for an array with shape (1586, 2420521) and data type float64`

my train set looks like:

<class 'pandas.core.frame.DataFrame'>
Index: 2420521 entries, n003bba8a98662e4 to nfff2bd38e397265
Columns: 1590 entries, era to erano
dtypes: Int8(1586), float32(1), int32(1), object(2)
memory usage: 7.2+ GB

and my validation:

<class 'pandas.core.frame.DataFrame'>
Index: 2401688 entries, n000101811a8a843 to nffd9c300c81a354
Columns: 1590 entries, era to erano
dtypes: Int8(1586), float32(1), int32(1), object(2)
memory usage: 7.2+ GB

So they are large, but should fit in memory, and I have trained other models on that data with my setup without memory limitations.

My question is: Can I do something to reduce the memory footprint?
I notice that my datatype is Int8 and the error message is about float64. Can I provide the data in a more memory efficient way? The features only take on very few integer numbers.

When digging through the library code a bit, I find examples like 

`self.validation = self.validation.copy()`

in file [datamodule](https://github.com/manujosephv/pytorch_tabular/blob/27493841eb559c48b979ec2adadfb2fb46ce0152/src/pytorch_tabular/tabular_datamodule.py#L298)

Are lines like this causing the memory increase? Is there a way to prevent that?  Thank you very much!

**Desktop (please complete the following information):**

- CPU RAM: 64GB
- GPU RAM: 12GB
- OS: Win 11
- IDE: VSCode
- pytorch_tabular version 1.0.1
- python 3.10.8

**Comment by manujosephv** [comment]
I admit the datamodule is not very memory efficient.. But most of the memory problems are from different preprocessing steps like normalizing etc.

If you can normalize the continuous variables in memory efficient prior to feeding it to the datamodule, and then use `normalize_continuous_features = False`, you can save some memory..

Also, if you do find any opportunities to make the datamodule more memory efficient, don't hesitate to raise a PR.

**Comment by simpsus** [comment]
Thank you very much for those insights, highly appreciated.
Currently me raising PRs is limited by my understanding, e.g. in the example above I have no idea what the reason behind copying the validation is. If and when I understand more I am motivated to give that back.
