### ISSUE TITLE
Making the package available on conda-forge

### ISSUE THREAD

**Issue by cheginit** [manujosephv/pytorch_tabular#167]
It would be great if this package becomes available on conda-forge. It should be relatively straightforward, I would be happy to help.

I checked all `pytorch_tabular` dependencies to ensure they are available on `conda-forge`. The only thing that needs to get resolved before adding `pyroch_tabular` to `conda-forge` is `pytorch-tabnet` v4 which is still not available (v3 is there). I ping the developer of the package on v4's [feedstock](https://github.com/conda-forge/pytorch-tabnet-feedstock/pull/2), so hopefully he will merge it soon.

**Comment by cheginit** [comment]
The maintainer of the `pytorch-tabnet` has merged v4!

**Comment by manujosephv** [comment]
That would be a great idea! @cheginit  . I personally have no experience with conda. If you can help with that, it'll be great!

**Comment by manujosephv** [comment]
@cheginit Is the issue with PyTorch installation resolved?

**Comment by cheginit** [comment]
Unfortunately, not yet. I will ping the conda-forge team again. But if they don't respond, I think we have to exclude a Windows build for now, to at least get the package on conda-forge.

**Comment by cheginit** [comment]
They just merged it! That was fast.

**Comment by manujosephv** [comment]
Awesome! Thanks a lot @cheginit  Finally, available on Conda ❤️❤️❤️

**Comment by manujosephv** [comment]
@cheginit So, This conda installation is for Linux and Mac only, right? And if we resolve that issue with windows, then it'll be enabled for windows as well?

**Comment by cheginit** [comment]
No. We don't need to do anything fir Windows, since we set `noarch` for the build option, so it's architecture-agnostic. It seems that there are some licensing issues with having `pytorch` for Windows on `conda-forge`. So, for installing packages that depend on `pytorch`, it's upon Windows users to install `pytorch`, for example, from the official `pytorch` repository when installing packages that depend on it. So, technically, right now, you should be able to install `pytorch-tabular` on Windows. I don't have a Windows machine to check though.

**Comment by manujosephv** [comment]
I have a windows machine and checked it in the morning and got this message:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-tabular

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - ```

**Comment by cheginit** [comment]
You're right. I just checked it on its [webpage](https://anaconda.org/conda-forge/pytorch-tabular) and there's only Linux and OSX. That's odd. We have to look into it.

**Comment by manujosephv** [comment]
@cheginit  I just noticed that there are two distributions in conda - pytorch_tabular - is the no arch one and pytorch-tabular for osx and linux!

**Comment by cheginit** [comment]
Right. The feedstock builds two versions; one with the underscore and one with dash. However, it's strange that their architecture versions are different. I'll take a look today.

**Comment by cheginit** [comment]
Just addressed the issue!

**Comment by manujosephv** [comment]
@cheginit I just released a new version on PyPi.. Would conda forge be updated automatically?
