### ISSUE TITLE
Question: Use the model without the configs

### ISSUE THREAD

**Issue by simpsus** [manujosephv/pytorch_tabular#175]
Is there a way (or available hints) to use a model (e.g. the FTTransformer) without the provided config, but with custom data/training code around it?

Thank you very much

**Comment by manujosephv** [comment]
Maybe if you give a few more details about the ask, I can try to help you out. I have used FTTransformers and other models in custom training and other special models.

**Comment by simpsus** [comment]
Basically I want the following snippet to run with one of the models defined in pytorch_tabular instead of the very simple stub

```
import torch
from loguru import logger
import numpy as np
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"
logger.debug(f"Device {device}")

class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.layer = torch.nn.Linear(1000,1)

    def forward(self, x):
        return self.layer(x).squeeze()
    
model = Model().to(device) # I want this to be one of the pytorch_tabular models
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
loss = torch.nn.MSELoss()
total_epochs = 50
for epoch in range(total_epochs):
    epoch_loss_train = 0
    model.train()
    for batch in range(1000):
        X = torch.tensor(np.random.rand(1000,1000).astype(np.float32)).to(device)
        y = torch.tensor(np.random.rand(1000).astype(np.float32)).to(device)
        pred_train = model(X)
        batch_loss = loss(pred_train, y)
        epoch_loss_train += batch_loss.item()
        optimizer.zero_grad()
        batch_loss.backward()
        optimizer.step()
    logger.debug(f'Epoch {epoch}: {epoch_loss_train}')
```

Thank you for the links. I found the code myself and tried to instantiate that model before posting this issue. I stumbled upon the BaseModel version expecting a DictConfig, but the fast ModelConfig I wipped up is not one of those. Then I found myself instantiating an onmiconf object with some values but during the building of the backbone there were some parameters missing the model expects. So ... again any hint on how to make that work is highly appreciated.

**Comment by manujosephv** [comment]
If you don't want to use the PyTorch Tabular training, then you can just pick up the barebones PyTorch backbone (inheriting from nn.Module). You will just need to stack a learn layer at the end to convert the output of the backbone to the dimension you want,

**Comment by simpsus** [comment]
Thank you I will try that. It is not that I do not _want_ to use pytorch tabular, it is that I cannot get it to work like I expect it to and I do not understand the inner workings enough to dig in and debug. So I resolve to rftm and that is a slow crawl of learning the basics by learning step by step
