### ISSUE TITLE
Example for find_learning_rate 

### ISSUE THREAD

**Issue by marcodelmoral** [manujosephv/pytorch_tabular#178]
Anyone have a working example for using find_learning_rate? Thanks in advance.

**Comment by manujosephv** [comment]
There are two ways:

1. set `auto_lr_find=True` in the Trainer config. this is supposed to automatically find the best LR and set
2. For more detailed analysis and to inspect the LR curve etc. you can use `find_learning_rate` method [ere](https://github.com/manujosephv/pytorch_tabular/blob/51734d8caff2e0ac066e56cf513d040e8d478880/src/pytorch_tabular/tabular_model.py#L968)
