### ISSUE TITLE
Error in Google Colab

### ISSUE THREAD

**Issue by franz101** [manujosephv/pytorch_tabular#19]
! pip install pytorch_tabular[all]

from pytorch_tabular import TabularModel

ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)

**Comment by franz101** [comment]
Possible solution:
https://colab.research.google.com/drive/1OAtSrTwUHMzvjBJ4PE8jS616b2_krsnW?usp=sharing#scrollTo=CgapnYrqPK5t

**Comment by Guthman** [comment]
The workaround that seems to work for me is installing the following versions:

`!pip install torchtext==0.9 --quiet
!pip install torch==1.8.1 --quiet
!pip install pytorch-lightning --quiet
!pip install pytorch_tabular==0.5.0 --quiet`

**Comment by manujosephv** [comment]
I'm guessing this is a PyTorch Lightning version compatibility issue.. glad to know that the workaround works.. I'll probably have to make an update to the way PyTorch Lightning is used in the library.. Seeing a lot of compatibility issues nowadays..

**Comment by manujosephv** [comment]
@Guthman This should be fixed now in the develop branch..

**Comment by manujosephv** [comment]
Fixed in v 0.6. Now in PyPi. Can you check and revert? `gpus` should be None for CPU and `-1` for using all GPUs

**Comment by manujosephv** [comment]
Closing the issue. Feel Free to reopen if it still persists.
