### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'clip'     

### ISSUE THREAD

**Issue by arita37** [manujosephv/pytorch_tabular#2]
torch                            1.6.0+cpu     

```
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 723, in train_step_and_backward_closure                              
    self.trainer.hiddens                                                                 
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 813, in training_step_and_backward                                   
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)                
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 320, in training_step                                                
    training_step_output = self.trainer.accelerator_backend.training_step(args)          
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pytorch_lightning\accelerators\cpu_accelerator.py", line 67, in training_step                                          
    output = self.trainer.model.training_step(*args)                                     
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pytorch_tabular\models\base_model.py", line 147, in training_step                                                      
    _ = self.calculate_metrics(y, y_hat, tag="train")                                    
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pytorch_tabular\models\base_model.py", line 104, in calculate_metrics                                                  
    y_hat = torch.clip(y_hat, min=0)                                                     
AttributeError: module 'torch' has no attribute 'clip'                                   
Epoch 0:   0%|          | 0/2 [00:00<?, ?it/s]   
```

**Comment by manujosephv** [comment]
This is due to lack of backward compatibility of the clip function in Pytorch. This should not be a problem in the 0.2.0.dev0 version which is on pypi now.

Can you try:
`pip install pytorch-tabular==0.2.0.dev0`

**Comment by manujosephv** [comment]
This is due to lack of backward compatibility of the clip function in Pytorch. This should not be a problem in the 0.2.0.dev0 version which is on pypi now.

Can you try:
`pip install pytorch-tabular==0.2.0.dev0`

**Comment by manujosephv** [comment]
This is due to lack of backward compatibility of the clip function in Pytorch. This should not be a problem in the 0.2.0.dev0 version which is on pypi now.

Can you try:
`pip install pytorch-tabular==0.2.0.dev0`

**Comment by manujosephv** [comment]
This is due to lack of backward compatibility of the clip function in Pytorch. This should not be a problem in the 0.2.0.dev0 version which is on pypi now.

Can you try:
`pip install pytorch-tabular==0.2.0.dev0`

**Comment by arita37** [comment]
Thanks.

Can you add CI testing on your example code ?
It’s easy to check when failing....

**Comment by manujosephv** [comment]
This is due to lack of backward compatibility of the clip function in Pytorch. This should not be a problem in the 0.2.0.dev0 version which is on pypi now.

Can you try:
`pip install pytorch-tabular==0.2.0.dev0` or wait for a couple of days. I'll be pushing this along with the `gpus` fix and an additional feature to use custom samplers in the dataloader.

**Comment by manujosephv** [comment]
> Thanks. Can you add CI testing on your example code ? It’s easy to check when failing....
> […](#)
> On Feb 7, 2021, at 10:06, manujosephv ***@***.***> wrote: ﻿ This is due to lack of backward compatibility of the clip function in Pytorch. This should not be a problem in the 0.2.0.dev0 version which is on pypi now. Can you try: pip install pytorch-tabular==0.2.0.dev0 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Actually, I do have CI testing through Travis CI, although not on the example codes. But all these issues should have ideally be caught, especially the gpus one because all the testing is done with `gpus=0`. And all those tests passed before deploying to pypi. These problems are due to version compatibilities, I guess.

**Comment by arita37** [comment]
Dependency requiremenr is incorrect.
should be > 1.7.0 for pytorch

Including example code
With nsample=100 and epoch=1
will help too

**Comment by manujosephv** [comment]
I've replaced the clip with clamp which is compatible.. so, may be torch>1.3 should be fine? 

And yeah.. will include the example code in tests. Pretty new to the whole CI side of things..

**Comment by manujosephv** [comment]
Pushed a new version fixing this. closing the issue
