### ISSUE TITLE
Possible issue in CI

### ISSUE THREAD

**Issue by manujosephv** [manujosephv/pytorch_tabular#210]
@Borda So, we have this [line](https://github.com/manujosephv/pytorch_tabular/blob/f93223050808d941ad342b9ad8058f1a5d813df5/.github/workflows/testing.yml#L31) which fixes the versions while testing, right?

When the user installs from pip, it'll be using the `>=` constraint, right? And will end up installing a higher version, which might not be captured in testing?

**Comment by Borda** [comment]
> When the user installs from pip, it'll be using the `>=` constraint, right? And will end up installing a higher version, which might not be captured in testing?

yes

**Comment by manujosephv** [comment]
Is that a problem? and if yes, can we resolve it by just not changing `>=` to `==`

**Comment by Borda** [comment]
Sad to see this being closed... =(

**Comment by manujosephv** [comment]
Ah! this one slipped below my radar and stale bot closed it.. Re-opened now..
