### ISSUE TITLE
When using min_epochs stdout is flooded with duplicate messages

### ISSUE THREAD

**Issue by Guthman** [manujosephv/pytorch_tabular#22]
**Describe the bug**
stdout is flooded with the message
`Trainer was signaled to stop but required minimum epochs (666) or minimum steps (None) has not been met. Training will continue... `
![Screenshot 2021-06-17 133909](https://user-images.githubusercontent.com/4036809/122389857-4ae57700-cf69-11eb-9ed5-677f13529c45.png)

**To Reproduce**
1. Use the option `min_epochs` in the TrainerConfig
2. Start training

**Expected behavior**
Print the line only once

**Desktop (please complete the following information):**
 - Colab

**Comment by manujosephv** [comment]
Unfortunately, this is a Pytorch Lightning thing Little I can do to sort it out..But I wouldn't call it an issue. What's happening is that you have enabled early stopping. And have set a minimum epoch.. So the warning says that although your early stopping criteria is telling the trainer to stop, it is still running to meet the min-epochs.

**Comment by Guthman** [comment]
Ah, I see. Let's close this one then.
