### ISSUE TITLE
Trainer does not support integer column names

### ISSUE THREAD

**Issue by Guthman** [manujosephv/pytorch_tabular#23]
**Describe the bug**
When passing a DataFrame that has integers as column names an error occurs:
`KeyError: "None of [Index(['0', '1'], dtype='object')] are in the [columns]"`

Where the column names are [0,1].

**To Reproduce**
Minimal example: https://colab.research.google.com/drive/1Os5vL2YupfH2JvduoTlQLaQ_mMafyui_?usp=sharing
(the last cell fails with `AttributeError: module 'pytorch_lightning.metrics' has no attribute 'functional'`, but I tested on another occasion that converting the column names to strings is a proper workaround)

**Expected behavior**
No error

**PyTorch Tabular version**
0.5.0

**Comment by manujosephv** [comment]
Interesting. The first issue should be a bug. I'll check it out. 

The second one is a PyTorch Lightning version issue. Recently, PT Lightning spun off the metrics into a separate library and thereby breaking a few things.. I'll include this in the next update to Pytorch Tabular..

**Comment by manujosephv** [comment]
@Guthman This should be fixed now in the develop branch.. Not able to publish to PyPi cause of my CI/CD pipeline which is currently with travics-ci.org. need to migrate to travis-ci.com or Github Actions.

**Comment by manujosephv** [comment]
Fixed in v 0.6. Now in PyPi. Can you check and revert? `gpus` should be `None` for CPU and `-1` for using all GPUs

**Comment by manujosephv** [comment]
Closing the issue. Feel Free to reopen if it still persists.
