### ISSUE TITLE
Kaggle Support for Pytorch Tabular

### ISSUE THREAD

**Issue by averma111** [manujosephv/pytorch_tabular#236]
<html>
<body>

41.1s | 13 | Traceback (most recent call last):
-- | -- | --
541.1s | 14 | File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 762, in _async_poll_output_msg
541.1s | 15 | msg = await ensure_async(self.kc.iopub_channel.get_msg(timeout=None))
541.1s | 16 | File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
541.1s | 17 | result = await obj
541.1s | 18 | File "/opt/conda/lib/python3.10/site-packages/jupyter_client/channels.py", line 224, in get_msg
541.1s | 19 | ready = await self.socket.poll(timeout)
541.1s | 20 | asyncio.exceptions.CancelledError

</body>
</html>

Job is failing due to above erro while submitting

**Comment by manujosephv** [comment]
I don't see anything PyTorch or PyTorch Tabular specific in the error messages
