### ISSUE TITLE
All tutorials use the same notebook

### ISSUE THREAD

**Issue by fcogidi** [manujosephv/pytorch_tabular#238]
**Describe the bug**
All the tutorial notebooks are the same.

**To Reproduce**
1. Go to `docs/tutorial` or https://pytorch-tabular.readthedocs.io/en/latest/tutorials/01-Basic_Usage/
1. View the notebooks.

**Expected behavior**
To see tutorials matching the title of each notebook.

**Comment by manujosephv** [comment]
@fcogidi I can see different notebooks in the tutorial. Although the starting of all the notebooks look the same, the content is different.

![image](https://github.com/manujosephv/pytorch_tabular/assets/10508493/4d138d85-fb3b-4ff3-84b6-0d769a39a15d)

**Comment by fcogidi** [comment]
I see. My bad for not checking properly.
