### ISSUE TITLE
Tutorial docs figure rendering 

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#25]
The figures in the tutorial docs are not currently rendered properly, but instead show a massive array of floats. For example, the MDN regression tutorial's first figure looks like this:

![image](https://user-images.githubusercontent.com/81476/122478746-93b02680-cf8f-11eb-84d4-af5e769e8f31.png)

This array takes up almost the entire web page, making reading very difficult, and of course the figure is not actually shown. Can these please be re-rendered?

**Comment by manujosephv** [comment]
Same as #11  Closing this. Will follow the initial issue..
