### ISSUE TITLE
TabularModel.fit( ) creates a directory saved_models in the project folder which stores .ckpt 

### ISSUE THREAD

**Issue by pranavvp16** [manujosephv/pytorch_tabular#278]
I want to know if there any is way to avoid this behaviour . I don't want the tabular_model.fit( ) to create the saved_models directory by default in my project folder as this behaviour will act similar in production too

**Comment by manujosephv** [comment]
Of course. There is a [parameter](https://github.com/manujosephv/pytorch_tabular/blob/20499a473056ff75474cda1d8a9d3ac7a105ed20/src/pytorch_tabular/config/config.py#L483) in `TrainerConfig` called `checkpoints_path` which can set where the checkpoints can be saved.
