### ISSUE TITLE
Code for Additional Models and Optuna Integration Question

### ISSUE THREAD

**Issue by CMobley7** [manujosephv/pytorch_tabular#29]
I ran across this great library, while I was searching for similar papers to the following on http://www.arxiv-sanity.com.

Revisiting Deep Learning Models for Tabular Data, https://arxiv.org/abs/2106.11959
Tabular Data: Deep Learning is Not All You Need, https://arxiv.org/abs/2106.03253

In section VI. Future Work of your paper, you mention adding additional models.

Revisiting Deep Learning Models for Tabular Data includes a GitHub page, https://github.com/yandex-research/rtdl/tree/main, where the authors have included python/PyTorch models for `SNN`, `TabNet`, `GrowNet`, `DCN2`, `AutoInt`, `MLP`, `NODE`, `ResNet`, and `FT-Transformer`, along with non-DL model `CatBoost` and `XGBoost`. They've also chosen to integrated `Optuna` to do hyperparameter tuning.

Tabular Data: Deep Learning is Not All You Need doesn't include a GitHub page for the paper, but they do link to code for the 1D-CNN, https://github.com/baosenguo/Kaggle-MoA-2nd-Place-Solution. `DNF-Net` appears to have been later renamed `Net-DNF` and the model can be found here, https://github.com/amramabutbul/DisjunctiveNormalFormNet unfortunately it's in `TF`, which makes sense given researchers at Google wrote the paper haha 

Adding `Net-DNF`, `FT-Transformer`, and `ResNet`, as well as possibly others, would be extremely beneficial since `Tabular Data: Deep Learning is Not All You Need` shows that the best performance comes from ensembling different models together with an `XGBoost` model.

Unfortunately, I'd have to get approval from my employer before I could submit a PR adding these models, which typically is a long process; so, I figured I'd post links to the code for now.

How do you plan on integrating `Optuna`? Were you planning on merely implementing `sampling` or `sampling` with `pruning` every epoch or so?

**Comment by manujosephv** [comment]
Awesome! Thanks for the links. In the develop branch, I have already added a few of these models - TabTransformer, and FT-Transformer are added. The roadmap has also been updated to be more specific to the models to be aded - DNF-Net is one of them The 1D CNN approach does look fascinating.. Will add it to the roadmap.

And it's a bummer that you can't contribute freely to open source. If you get the approval, do let me know. Would love to have you add a few of these models.

And optuna.. is currently not fleshed out. But Pruning is definitely in the plan..
