### ISSUE TITLE
SHAP value calculation

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#32]
Has anyone had success extracting SHAP values from `pytorch_tabular` models? The [`shap` package](https://github.com/slundberg/shap) does not appear to be compatible, since even its very general `KernelExplainer` class cannot cope with a tabular model. 

Given that pytorch_tabular is a high-level package, it would be a great addition to have SHAP calculation built in.

**Comment by fonnesbeck** [comment]
I finally solved this: When you create a `KernelExplainer` in `shap` you need to include a `keep_index=True` flag on initialization, otherwise it throws the DataFrame indexes out. This is not documented in `shap`, unfortunately.

**Comment by manujosephv** [comment]
Great work!... Can you add a notebook or tutorial on how to use KernelExplainer for PyTorch Tabular? I think a lot of people would benefit from that.

**Comment by fonnesbeck** [comment]
I'd be happy to!

**Comment by manujosephv** [comment]
just a gentle reminder. the notebook/tutorial on using Kernel Explainer would be awesome!
