### ISSUE TITLE
Can't import TabularModelTuner from tabular_model_tuner 

### ISSUE THREAD

**Issue by JonathanBhimani-Burrows** [manujosephv/pytorch_tabular#359]
**Describe the bug**
Following what is here 
https://pytorch-tabular.readthedocs.io/en/latest/tutorials/09-Low-level%20API%20Usecases%28CV%2C%20Tuning%2C%20and%20more%29/
I was attempting to test the TabularModelTuner
When importing, I received this error 
<img width="388" alt="image" src="https://github.com/manujosephv/pytorch_tabular/assets/44709223/cf00f38c-85c0-451d-8b34-d640f9aac9bd">
Note: I am on Google Colab, but all pytorch_tabular and pytorch_tabular extras should be up to date 

**To Reproduce**
Run from pytorch_tabular.tabular_model_tuner import TabularModelTuner

**Expected behavior**
successful import 

**Screenshots**

**Desktop (please complete the following information):**

- OS:Windows 10
- Browser Edge
- Version 
- NOTE: using google Colab

**Smartphone (please complete the following information):**

- Device: \[e.g. iPhone6\]
- OS: \[e.g. iOS8.1\]
- Browser \[e.g. stock browser, safari\]
- Version \[e.g. 22\]

**Additional context**

**Comment by manujosephv** [comment]
Tuner is a feature which is yet to be pushed to PyPi. So if you have installed using 'pip install pytorch_tabular' you won't get it. You will need to install from git directly to test that out. Just wanted to confirm if you have done that.

**Comment by JonathanBhimani-Burrows** [comment]
Good point 
Is this the same with the Gandalf model from this paper? 
If I want to install directly from git, do I need any of pytorch_tabular or pytorch_tabular[extra]? Or will the git installation include what I need for both?

**Comment by JonathanBhimani-Burrows** [comment]
For those interested, both the tabular model tuner and the gandalf model work properly if installed from git directly (no need to install either of the pytorch_tabular or pytorch_tabular['extras'])
Thanks again for the help - closing the ticket
