### ISSUE TITLE
Unable to Install on Windows Due to scikit-learn Error

### ISSUE THREAD

**Issue by BSalita** [manujosephv/pytorch_tabular#36]
I'm unable to install pytorch_tabular on Windows due to scikit-learn error. Installation worked fine when installing under WSL.

  copying sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz -> build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292
  error: could not create 'build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz': No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn which use PEP 517 and cannot be installed directly

**Comment by BSalita** [comment]
The same error message appears with your suggested command. However, the following commands work.
pip install scikit-learn

--or--
pip install scikit-learn==0.24.2

How can I override installing of 0.23.2 and have pip install 0.24.2 instead when I execute:
pip install pytorch_tabular
Seems like your install is locked to 0.23.2.
    On Wednesday, August 11, 2021, 01:27:46 PM GMT+2, manujosephv ***@***.***> wrote:  
 
 


I suspect an environment issue.. are you able to install scikit-learn individually?

pip install scikit-learn==0.23.2

**Comment by BSalita** [comment]
After hours of experiments, I'm concluding Windows installation is utterly broken.

There's multiple issues:
1. Testers never tried a standard `pip` install on Windows. If they did, they'd immediately see the failure.
2. The `scikit-learn` package is broken, won't install itself which causes `pytorch_tabular` install to fail.
3. The `requirments.txt` contains some packages which are locked to a version number (== 0.23.2) instead of (>= 0.23.2). Thus creating a fragile installation guaranteed not to grow old well.

I've been able to workaround the installation issue by `pip download pytorch_tabular`, ungziping, untaring, drilling down into the directory containing setup.py and requirements.txt. Editing requirements.txt by removing version requirements for `category-encoders` and `scikit-learn` and saving the file. Finally, `python setup.py install`. Now the package will completely installed.

This article criticizes developers for creating fragile versioning:
https://stackoverflow.com/questions/15031694/installing-python-packages-from-local-file-system-folder-to-virtualenv-with-pip

**Comment by manujosephv** [comment]
Am sorry you had to face this issue @BSalita . I work on a windows machine and have developed this on a Windows Machine as well. It works fine on my machine. The CI/CD pipeline is run on Linux, so I hope that should cover the Linux installation as well.  The key issue here is that `scikit-learn` is not getting installed for you for some reason. I guess you should raise an issue with `scikit-learn` for this.

And from PyTorch Tabular side, I can experiment with letting scikit-learn>=0.23.2 and running the build process.

**Comment by manujosephv** [comment]
Quick google search got me these possible causes:
1.  Have you tried upgrading your pip?  https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe
2. Which version of Python are you using? https://github.com/scikit-learn/scikit-learn/issues/18852

**Comment by BSalita** [comment]
I'm afraid neither of the two links fixed the issue. There were many good ideas though. In the end, addressing the three issues I've mentioned is the current best solution.

**Comment by manujosephv** [comment]
strange.. I'll unfreeze the sklearn next release. That should resolve this issue..

**Comment by manujosephv** [comment]
Have relaxed the sci-kit learn dependency and pushed a new release. Hopefully this resolves the issue.

**Comment by BSalita** [comment]
I'm now able to install pytorch-tabular on Windows without issue.
