### ISSUE TITLE
Can the model architecture of semi-supervised learning be customized? 

### ISSUE THREAD

**Issue by yangkaixin233** [manujosephv/pytorch_tabular#368]
Thanks to the authors for their excellent work, and I would like to ask if there is a tutorial on this issue.

**Comment by manujosephv** [comment]
@yangkaixin233  Thank you. 

The SSL part is sort of experimental and not very mature yet. Although it's possible to customize the SSL model, there is no tutorial available. But I guess you can check out the code for DAE [here](https://github.com/manujosephv/pytorch_tabular/blob/main/src/pytorch_tabular/ssl_models/dae/dae.py) and try to customize it.

**Comment by yangkaixin233** [comment]
Thank you soooooo much!
