### ISSUE TITLE
test_dataloaders is Deprecated in pytorch_lightning

### ISSUE THREAD

**Issue by BSalita** [manujosephv/pytorch_tabular#38]
You've probably already have seen this warning. No hurry. Very low priority issue for me.

C:\Users\bsali\anaconda3\envs\pt\lib\site-packages\pytorch_lightning-1.4.2-py3.9.egg\pytorch_lightning\trainer\trainer.py:679: LightningDeprecationWarning: `trainer.test(test_dataloaders)` is deprecated in v1.4 and will be removed in v1.6. Use `trainer.test(dataloaders)` instead.

**Comment by manujosephv** [comment]
Upgraded to 1.8.* and it still hasn't broken. :) Closing
