### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by unolife** [manujosephv/pytorch_tabular#380]
data_config = DataConfig(
            target=[target_column],
            continuous_cols=continuous_cols,
            categorical_cols=categorical_cols,
        )
**Describe the bug**

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: \[e.g. iOS\]
- Browser \[e.g. chrome, safari\]
- Version \[e.g. 22\]

**Smartphone (please complete the following information):**

- Device: \[e.g. iPhone6\]
- OS: \[e.g. iOS8.1\]
- Browser \[e.g. stock browser, safari\]
- Version \[e.g. 22\]

**Additional context**

**Comment by manujosephv** [comment]
Would you be able to provide more information?

**Comment by manujosephv** [comment]
Closing this, Do re-open if you feel the need to.
