### ISSUE TITLE
ValueError: y contains previously unseen labels

### ISSUE THREAD

**Issue by unolife** [manujosephv/pytorch_tabular#381]
**Describe the bug**
I wanna do binary classification, but I got this error
ValueError: y contains previously unseen labels: [-1.671504692016799]

data_config = DataConfig(
    target=[target_column],
    continuous_cols=continuous_cols,
    categorical_cols=categorical_cols,
)
trainer_config = TrainerConfig(
    auto_lr_find=True,
    batch_size=1024,
    max_epochs=100,
)
optimizer_config = OptimizerConfig()
experiment_config = ExperimentConfig(project_name=seg_name)

model_config = TabNetModelConfig(
    task='classification',
    metrics=['accuracy', "f1_score"],
    metrics_params=[dict(task="multiclass", num_classes=2), dict(task="multiclass", num_classes=2)]
)

model = TabularModel(
            model_config=model_config,
            data_config=data_config,
            optimizer_config=optimizer_config,
            trainer_config=trainer_config,
            experiment_config=experiment_config,
        )
model.fit(train=train, validation=valid)
print(model.evaluate(test))

target have values 0 or 1, how can I fix?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manujosephv** [comment]
Can you check if the target column is part of the continuous or categorical features?

**Comment by manujosephv** [comment]
Closing this, Do re-open if you feel the need to.

**Comment by HernandoR** [comment]
same problem meet, target column is not part of continuous or categorical features
