### ISSUE TITLE
Unable to load model trained with custom loss function

### ISSUE THREAD

**Issue by kojingying** [manujosephv/pytorch_tabular#393]
**Describe the bug**
Hi, thanks for your great work!! I have an issue when trying to load the trained model trained with custom loss, with refer to this documentation: https://pytorch-tabular.readthedocs.io/en/latest/tutorials/06-Imbalanced%20Classification/. When I try to load the model back after I save  the model, there is an error.

**To Reproduce**
weighted_loss = get_class_weighted_cross_entropy(train["target"].values.ravel(), mu=0.1)

tabular_model.fit(train=train, validation=val, loss=weighted_loss)
tabular_model.save_model('saved_model')
tabular_model.load_model('saved_model') --> got issue

Error:
RuntimeError: Error(s) in loading state_dict for CategoryEmbeddingModel:
  Unexpected key(s) in state_dict: "custom_loss.weight", "loss.weight"

**Comment by manujosephv** [comment]
Good catch! Will take a look at this

**Comment by manujosephv** [comment]
Have pushed a fix for this. Without updating the code, you can get it to work by passing `strict=False` to the `load_model`.
#415 fixes this
