### ISSUE TITLE
Error when using load_from_checkpoint : TypeError: _prepare_trainer() missing 2 required positional arguments: 'max_epochs' and 'min_epochs'

### ISSUE THREAD

**Issue by N950** [manujosephv/pytorch_tabular#4]
model.model = TabularModel.load_from_checkpoint( "/data/torch_checkpoint")
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\pytorch_tabular\tabular_model.py", line 682, in load_from_checkpoint
    tabular_model._prepare_trainer()
TypeError: _prepare_trainer() missing 2 required positional arguments: 'max_epochs' and 'min_epochs'

**Comment by manujosephv** [comment]
I'm almost about to push in a new version of the library with new models, and other features.. This bug is already fixed in that. If possible, wait for that. Else, you can get the latest code from `develop` branch. This bug is resolved in that.

**Comment by N950** [comment]
Thanks for responding,
I'll test the develop branch, for now a colleague just hard coded a max/min epochs in the _prepare_trainer() call

**Comment by manujosephv** [comment]
Have pushed 0.4.0 to PyPi. It should resolve this issue. Can you confirm if it is resolved so that we can close this issue?

**Comment by N950** [comment]
Yes, resolved in 0.4.0
tabular_model._prepare_trainer() no longer raise that error

Thank you
