### ISSUE TITLE
Disabling progress bars for model fitting

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#41]
It would be helpful if the progress bar for model fitting could be disabled. This is particularly relevant when trying to optimize model hyperparameters, when the following occurs:

<img width="1276" alt="Screen Shot 2021-09-15 at 3 35 38 PM" src="https://user-images.githubusercontent.com/81476/133505948-9fc681ae-1c67-4d9f-8377-9e460c9c4af0.png">

Passing a `disable_pbar` or similar flag to `fit` would be a nice feature.

**Comment by manujosephv** [comment]
The progress bar is actually coming from PyTorch Lightning under the hood. But there is a parameter that can turn off the progress bar, but it is not exposed in the PyTorch Tabular API. Will try to expose most of the functionality from PyTorch Lightning Trainer in the next update

**Comment by manujosephv** [comment]
This is coming as part of the next release. Closing the issue

**Comment by ooghry** [comment]
@fonnesbeck Could you please share your code for hyperparameters optimization?
