### ISSUE TITLE
Open discussion: Wandb.finish

### ISSUE THREAD

**Issue by HernandoR** [manujosephv/pytorch_tabular#416]
**Is your feature request related to a problem? Please describe.**
manual wandb.finish after training

**Describe the solution you'd like**
add wandb.finish() at the end of model.fit

**Describe alternatives you've considered**
not sure if needed

**Comment by manujosephv** [comment]
While I get the intent, there may be some cases where you don't want to call `wandb.finish()`. Maybe you want to evaluate on new data and log the metrics to the same experiment. But, I guess we can include a parameter in the `fit` method and call `wandb.finish()` at the end of the training based on that parameter. Would you be willing to raise a PR for that?
