### ISSUE TITLE
Multi-Target Classification

### ISSUE THREAD

**Issue by YonyBresler** [manujosephv/pytorch_tabular#430]
**Is your feature request related to a problem? Please describe.**
Currently, regression allows for multi-target training, while classification only supports a single target.

**Describe the solution you'd like**
Add support for multi-target classification, including data handling, output layer size shaping, and appropriate loss.

**Describe alternatives you've considered**
You currently need to train multiple models, which is both slower and may not get the same performance as learning a common embedding

**Additional context**
I'm prepared to contribute this feature myself, but wanted to check:

1. That there is no unworkable/undesirable roadblock that prevents this from being possible at this time
2. That if I were to complete it, that the community is interested in integrating this feature

**Comment by manujosephv** [comment]
@YonyBresler This has been something the community has requested for in the past as well and would be an awesome addition. I can assure you that your contribution would be most welcomed. I can work with you for the PR.

**Comment by YonyBresler** [comment]
Thanks for your feedback @manujosephv , I finished a first pass at this, and have a PR in #441 , happy to hear your (or any other community member) feedback
