### ISSUE TITLE
The architecture of TabularModelTuner best_model does not match best_params

### ISSUE THREAD

**Issue by kaboroevich** [manujosephv/pytorch_tabular#434]
**Describe the bug**
The model in pytorch_tabular.tabular_model_tuner.OUTPUT.best_model is not the model defined by pytorch_tabular.tabular_model_tuner.OUTPUT.best_params but instead the model defined by the hyperparameter placeholders when constructing the various configs.

**To Reproduce**
1. Follow [How-To-Guide for Hyperparameter Turning](https://pytorch-tabular.readthedocs.io/en/latest/tutorials/10-Hyperparameter%20Tuning/)
2. Replace the search space with the placeholder parameters removed
```
search_space = {  
    "model_config__layers": ["1024-512-256", "1024-512-128"],  
    "model_config.head_config__dropout": [0.2, 0.3],  
     "trainer_config__batch_size": [1024, 2048, 4096],  
     "optimizer_config__optimizer": ["RAdam", "AdamW"],  
} 
```
3. The output of the tune method will report the best parameters from the search_space, but the best model will have the parameters defined in CategoryEmbeddingModelConfig()

**Expected behavior**
That the architecture of `.best_model` matches `.best_params`

**Screenshots**
![image](https://github.com/manujosephv/pytorch_tabular/assets/872618/e69855db-ef62-446a-9460-898439ee12f6)

**Additional context**
pytorch_tabular.__version__ = '1.1.0'

**Comment by manujosephv** [comment]
@ProgramadorArtificial Do you want to take a look at this?

**Comment by ProgramadorArtificial** [comment]
Hello!
This has been fixed here: https://github.com/manujosephv/pytorch_tabular/pull/387. But the PR is not in the main version, so to solve the problem you need to clone the repository and install Python Tabular using "pip install .[extra]" or wait for the next version to be released :)
![image](https://github.com/manujosephv/pytorch_tabular/assets/130674366/c56349af-ac97-438d-aad3-243fc15397de)

**Comment by kaboroevich** [comment]
Thank you for the information. I will clone the repo as suggested.
