### ISSUE TITLE
Is there a way to use a dataframe as an argument for the `baselines` parameter of the `explain` method?

### ISSUE THREAD

**Issue by liganega** [manujosephv/pytorch_tabular#467]
Calculating attribution based on `IntegratedGradients` for `FTTransformerf` requires `baseslines`.
Is there a way to use a dataframe with the same features as baselines?
For example, a dataframe which is a kind of subset of the input dataframe!

**Comment by manujosephv** [comment]
Integration with Captum is limited. But if you can show me an example of what you are trying to do, I can try to help, or even include the feature in an upcoming release
