### ISSUE TITLE
Save TabularModel to ONNX

### ISSUE THREAD

**Issue by beavisluck** [manujosephv/pytorch_tabular#480]
### Discussed in https://github.com/manujosephv/pytorch_tabular/discussions/473

<div type='discussions-op-text'>

<sup>Originally posted by **beavisluck** August 29, 2024</sup>
im trying to save a TabularModel to onnx using save_model_for_inference() unfornately it doesn't work as shown below 
![image](https://github.com/user-attachments/assets/931d045a-9eb0-43f5-b29d-24faf846f6f3)
can anyone show me how to use that function properly? and is there any missing feature that i need to keep in mind when converting to onnx? thanks</div>

**Comment by beavisluck** [comment]
so it turns out, i haven't execute the fitting process, however after TabularModel.fit, a new error message emerges
![image](https://github.com/user-attachments/assets/f59fed51-0ed8-46ab-bf45-7bab6e3ed642)

**Comment by manujosephv** [comment]
ONNX export is highly experimental and isn't guaranteed to work cause there might be operations in some architectures which doesn't play well with onnx export. #442 is a related issue which might help you..
