### ISSUE TITLE
Denoising AutoEncoder  link URL is broken

### ISSUE THREAD

**Issue by ramakrse** [manujosephv/pytorch_tabular#502]
In the readme document [Denoising AutoEncoder](https://www.kaggle.com/code/faisalalsrheed/denoising-autoencoders-dae-for-tabular-data) is broken. Request a fix

**Comment by ramakrse** [comment]
@dosu https://www.kaggle.com/code/faisalalsrheed/denoising-autoencoders-dae-for-tabular-data  does not exist. It says that We can't find that page

**Comment by manujosephv** [comment]
@ramakrse For some reason the kaggle notebook that was linked was taken down. I found another one which is also relevant.
https://www.kaggle.com/code/springmanndaniel/1st-place-turn-your-data-into-daeta

**Comment by manujosephv** [comment]
Fixed in #511. Closing
