### ISSUE TITLE
NODE's predict method sometimes takes a long time

### ISSUE THREAD

**Issue by gagagio** [manujosephv/pytorch_tabular#51]
**Describe the bug**
NODE's predict method sometimes takes a long time. Is there some kind of processing that needs to be done before `predict`? Thank you. 

**To Reproduce**
The code to reproduce the behavior is [here](https://www.kaggle.com/tsano430/pytorch-tabular-node).

**Comment by robburdon** [comment]
I suspect this is because inference in`predict`is not running on the GPU.
