### ISSUE TITLE
Migrate to Github Actions.

### ISSUE THREAD

**Issue by wsad1** [manujosephv/pytorch_tabular#52]
pytorch-tabular currently uses travis and tox for CI/CD, the plan is to move this to github-actions.

**Describe the solution you'd like**
The current CI/CD pipeline uses flake8 for linting, and tests the code with pytest on python 3.7, 3.6 and 3.8. After which the package is deployed to pypi.

The migration to actions can be split into two tasks.

- [x] Create and single/separate workflow for testing and linting.
- [ ] Create a workflow for deployment that depend on the linting and testing workflow(s). It's not very straightforward to have one workflow depend on another, so for starts we could have just one workflow with 3 jobs for testing, linting and deployment.

Any feedback on this plan is welcome :).

**Comment by manujosephv** [comment]
Looks Good @wsad1

**Comment by manujosephv** [comment]
#116 Closed this
