### ISSUE TITLE
Regression example is not viewable in github

### ISSUE THREAD

**Issue by gdevos010** [manujosephv/pytorch_tabular#64]
**Describe the bug**
reduce regression example load time so its viewable in github

**To Reproduce**
https://github.com/manujosephv/pytorch_tabular/blob/main/examples/regression_with_MDN.ipynb

**Expected behavior**
readable similar to the classification example 
https://github.com/manujosephv/pytorch_tabular/blob/main/examples/classification_with_NODE.ipynb

**Screenshots**
![image](https://user-images.githubusercontent.com/15316026/152088246-f971453e-88b5-4e0d-9b2e-cf99415e9336.png)

**Comment by manujosephv** [comment]
Github sometimes have problems rendering notebooks. I usually prefer nbviewer. It loads notebooks much faster..

https://nbviewer.org/github/manujosephv/pytorch_tabular/blob/main/examples/classification_with_NODE.ipynb

P.S: The notebook opens fine for me. But like I said, it really depends on GitHub's mood. :-p
