### ISSUE TITLE
metrics_params get overwritten 

### ISSUE THREAD

**Issue by gdevos010** [manujosephv/pytorch_tabular#65]
**Describe the bug**
`metrics_params` get overwritten in regression. This is also a problem if two metrics are passed in

https://github.com/manujosephv/pytorch_tabular/blob/1af8454097450ae16314861b123a8e8ddcfc0956/pytorch_tabular/config/config.py#L642-L646

**Expected behavior**
```
self.metrics_params = [{}] if self.metrics_params is None else self.metrics_params
```

**Comment by manujosephv** [comment]
Good catch!.. This is actually a bug that I fixed yesterday. `main` branch has the fix for this. Haven't pushed it to a release yet

```python
self.metrics_params = (
                [{} for _ in self.metrics]
                if self.metrics_params is None
                else self.metrics_params
            )
```
