### ISSUE TITLE
Wrong pandas version in requierments?

### ISSUE THREAD

**Issue by redreamality** [manujosephv/pytorch_tabular#68]
**Describe the bug**
Not necessarily a bug. The dependency of pandas == 1.1.5 is a really obsolete version, (and also many other packages)
For pandas I read through the source and didn't find a version specific usage. Considering change it to pandas >=1.1.5?

**Comment by manujosephv** [comment]
Will definitely test after relaxing the dependency and eliminate that in the next release.. Thanks for pointing out..

**Comment by kevin1kevin1k** [comment]
+1 for this.
Seems to be fixed by https://github.com/manujosephv/pytorch_tabular/commit/498826050f8af513ce9fbf75df3a91b02b09bffd

**Comment by manujosephv** [comment]
Closing. Should be fixed in 1.0.*
