### ISSUE TITLE
[New Feature] Add Semi-supervised Models like VIME

### ISSUE THREAD

**Issue by arita37** [manujosephv/pytorch_tabular#7]
Hello,

Can you add [VIME ](https://github.com/jsyoon0823/VIME)model ?
Should be straightforward.

Thx

**Comment by manujosephv** [comment]
VIME and other self-supervised frameworks require a bit of work in the structure. Definitely on the roadmap

**Comment by arita37** [comment]
Good.
Defintively it would be a good step.
More, Self-Super. are coming.
