### ISSUE TITLE
This Page does not exist!

### ISSUE THREAD

**Issue by namankhetan** [manujosephv/pytorch_tabular#73]
https://github.com/manujosephv/pytorch_tabular/blob/7f9155b7fba6372dd3b1be4d100669795a79e465/pytorch_tabular/config/config.py#L246

Can you please confirm if the below link is the correct replacement of the link in question-
https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-class-api

thanks.

**Comment by manujosephv** [comment]
yes @namankhetan. I guess Pytorch Lightning changed the links to their documentation. Can you raise a PR?

**Comment by namankhetan** [comment]
hey @manujosephv, i have raised a PR for the issue. 
Many thanks for such a wonderful library.

**Comment by manujosephv** [comment]
Thanks for the PR, but unable to merge because it had additional changes apart from the doc change. Anyways, I'll be updating the documentation link as part of a next release..  closing this now.
