### ISSUE TITLE
Request to un-pin the PyTorch Lightning Dependency

### ISSUE THREAD

**Issue by ethanwharris** [manujosephv/pytorch_tabular#76]
**Is your feature request related to a problem? Please describe.**

We integrate PyTorch-Tabular in [Lightning-Flash](https://github.com/PyTorchLightning/lightning-flash) thanks to the work of @Actis92

It's awesome!!! Giving us access to a great range of tabular models. However, we've run in to issues where users who install flash for tabular have to have the specific PL version that is pinned by PyTorch-Tabular (e.g. 1.3.6 in the latest release, 1.5.10 on master).

**Describe the solution you'd like**

Would it be an option to just set a minimal version of PL in PyTorch-Tabular but allow for newer? This would make it much more flexible for use as a dependency in other projects.

If there are concerns about compatibility with latest PL versions, I would be happy to help with adding PyTorch-Tabular to the Ecosystem CI (see #63 for details) so that you get nightly GPU tests running with latest PL. Let me know your thoughts :smiley:

**Describe alternatives you've considered**

We will just live with the limitation in Flash 😆

**Comment by manujosephv** [comment]
That's great news! I can try to unpin PL version and see if that causes a problem. It shouldn't.

I wasn't aware that @Actis92  was integrating PytorchTabular to Flash. I am currently working on some refactoring of the code to make it cleaner and more modular. Although I have tried to keep all the internal APIs as constant as possible, I haven't kept that as a rule. Only the external APIs were kept the same. So, I guess after I push in the new update (which may take a while), we may want to re-look at the integration to see if it causes some problem upstream.

**Comment by ethanwharris** [comment]
Awesome! Thanks for your help.

> So, I guess after I push in the new update (which may take a while), we may want to re-look at the integration to see if it causes some problem upstream.

Sounds good, happy to assist if I can 😃

**Comment by manujosephv** [comment]
@ethanwharris  @Actis92 Just a heads-up. I have pushed in some updates. Major updates to the code is done. Just working on updating documentations etc. Once that is done I'll release a new version. Maybe we can check if the Flash integration has any problems after that..
