### ISSUE TITLE
Thrown "TypeError: issubclass() arg 2 must be a class or tuple of classes" after fitting model

### ISSUE THREAD

**Issue by ohleevah** [manujosephv/pytorch_tabular#78]
I have no problem running the code [as described here](https://pytorch-tabular.readthedocs.io/en/latest/tutorials/01-Basic_Usage/) but when I format my data the same way, I receive the following error: 

```
>>> tabular_model.fit(train=df_train, validation=df_val)
Global seed set to 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_tabular/tabular_model.py", line 431, in fit
    train_loader, val_loader = self._pre_fit(
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_tabular/tabular_model.py", line 375, in _pre_
    self.callbacks = self._prepare_callbacks()
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_tabular/tabular_model.py", line 239, in _prepllbacks
    model_checkpoint = pl.callbacks.ModelCheckpoint(
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", lin in __init__
    self.__init_ckpt_dir(dirpath, filename, save_top_k)
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", lin in __init_ckpt_dir
    rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py", line 49,apped_fn
    return fn(*args, **kwargs)
  File "/cluster/home/loliva/anaconda3/envs/loliva_env/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py", line 69,arn
    warnings.warn(*args, **kwargs)
TypeError: issubclass() arg 2 must be a class or tuple of classes
```
For data privacy reasons I can't post the exact dataset here, but it is generally structured as follows: 

**Here is my training data:**
![image](https://user-images.githubusercontent.com/85132953/170120297-a8fc779e-0645-42be-bee3-5833ab9e4abd.png)

**And here is the simulated data in the tutorial:**

![image](https://user-images.githubusercontent.com/85132953/170120457-448881d1-61a2-4db0-973c-2ba1a13fe118.png)

**And here is my modelling code (nearly identical to the tutorial):**
```
number_cols = list(range(0,577))
cont_names = []
for i in number_cols:
    cont_names.append(str(i))

data_config = DataConfig(
    target=['arrhyth_event'], #target should always be a list. Multi-targets are only supported for regression. Multi-Task Classification is not implemented
    continuous_cols=cont_names,
    #categorical_cols=cat_col_names,

trainer_config = TrainerConfig(
    auto_lr_find=False, # Runs the LRFinder to automatically derive a learning rate
    batch_size=1024,
    max_epochs=100,
    gpus=None,  #index of the GPU to use. -1 means all available GPUs, None, means CPU
)


optimizer_config = OptimizerConfig()


model_config = CategoryEmbeddingModelConfig(
    task="classification",
    layers="1024-512-512",  # Number of nodes in each layer
    activation="LeakyReLU", # Activation between each layers
    learning_rate = 1e-3,
    metrics=["f1","accuracy"], 
    metrics_params=[{"num_classes":2},{}]
)

tabular_model = TabularModel(
    data_config=data_config,
    model_config=model_config,
    optimizer_config=optimizer_config,
    trainer_config=trainer_config)

tabular_model.fit(train=df_train, validation=df_val)
```

**Comment by manujosephv** [comment]
It's difficult to debug an issue unless I can replicate it at my end. Unless you can prepare a way I can replicate it at my end, I doubt I'll be of much help.

1. Which version of pytorch_tabular are you using?
2. You mentioned you are able to run the code in colab, but not when you use your data. These both runs were made on the same machine? Or is it that one was done on colab and another on your local machine?

The error seems to be coming from a place which doesn't have anything to do with the data at all and hence a little strange.

**Comment by ohleevah** [comment]
> 1. Which version of pytorch_tabular are you using?

For completeness sake, here's the versions of all the required packages ([as described in requirements.txt](https://github.com/manujosephv/pytorch_tabular/blob/main/requirements.txt)). 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/laura/AppData/Local/Temp/msohtmlclip1/02/clip.htm">
<link rel=File-List
href="file:///C:/Users/laura/AppData/Local/Temp/msohtmlclip1/02/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Requirement | Installed version
-- | --
torch>=1.0.4 | 1.11.0
category-encoders==2.2.2 | 2.2.2
numpy>=1.17.2 | 1.21.5
pandas==1.1.5 | 1.1.5
scikit-learn>=0.23.2 | 0.24.2
pytorch-lightning==1.5.9 | 1.5.9
omegaconf>=2.0.1 | 2.1.2
torchmetrics>=0.3.2 | 0.6.0
tensorboard>=2.2.0, !=2.5.0 | 2.6.0
pytorch-tabnet==3.0.0 | 3.0.0
PyYAML<=5.4.1, >=5.1 | 5.4.1
matplotlib>3.1 | 3.4.1
ipywidgets | 7.7.0
dataclasses;python_version=='3.6' | 3.9
einops==0.3.0 | 0.3.0
rich>= 10.2.2 | 12.4.4



</body>

</html>

As you can see, all requirements are satisfied, except that I am running this on Python v3.9 and not v3.6. Do you think that is the cause?

Also perhaps of note, when I re-installed pytorch-lightning to ensure I had v1.5.9, this error popped up:

```
Installing collected packages: pytorch_lightning

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytorch-tabular 0.7.0 requires pytorch-lightning==1.3.6, but you have pytorch-lightning 1.5.9 which is incompatible.

Successfully installed pytorch_lightning-1.5.9
```


> 2. You mentioned you are able to run the code in colab, but not when you use your data. These both runs were made on the same machine? Or is it that one was done on colab and another on your local machine?

I'm not using colab or my local machine. Both were run on a Slurm-managed remote computing cluster associated with my workplace.

**Comment by manujosephv** [comment]
@ohleevah Can you try with the new version 1.0.* and see if the error persists? Reopen if its there..
