### ISSUE TITLE
Value Error when categorical column is of dtype "Categorical"

### ISSUE THREAD

**Issue by manujosephv** [manujosephv/pytorch_tabular#79]
**Describe the bug**
When the categorical columns are of dtype Categorical in pandas, it throws this error.
`ValueError: Cannot setitem on a Categorical with a new category, set the categories first`

**Comment by DominikFilipiak** [comment]
Workaround: make sure that in your data frame all categorical columns are casted to string. 
```{python}
for c in cols_category:
    df[c] = df[c].astype("string") 
    df[c].fillna("na", inplace=True)
```

**Comment by snehilchatterjee** [comment]
Hi, I managed to fix the issue by modifying `src/pytorch_tabular/tabular_datamodule.py` and `src/pytorch_tabular/categorical_encoders.py` by adding the following:

```python
category_cols = data[cat_cols].select_dtypes(include='category').columns
data[category_cols] = data[category_cols].astype('object')
```

Can I open a PR for this, or are further adjustments needed in other files that I might have missed?

**Comment by manujosephv** [comment]
Yes.. This is still open... Feel free to raise a PR

**Comment by snehilchatterjee** [comment]
@manujosephv I have raised the PR. Let me know if any changes are needed before merging. Also while you are at it I'd appreciate it if you could also review my previous PR.
