### ISSUE TITLE
ft_transformer error when there are no categorical columns

### ISSUE THREAD

**Issue by GillianGrayson** [manujosephv/pytorch_tabular#87]
Hi!

I am trying to use some models from your repository and got the following error:

```
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FTTransformerBackbone' object has no attribute 'cont_embedding_layer'
```

If I understood correctly under this condition:
https://github.com/manujosephv/pytorch_tabular/blob/0544fba3c173c5d2bf5153ef189243ff6e0a186f/pytorch_tabular/models/ft_transformer/ft_transformer.py#L64

the following layer for continuous columns (not categorical) is created:
https://github.com/manujosephv/pytorch_tabular/blob/0544fba3c173c5d2bf5153ef189243ff6e0a186f/pytorch_tabular/models/ft_transformer/ft_transformer.py#L95

When the condition is not met, this layer is not created. However, it will still be called on this line:
https://github.com/manujosephv/pytorch_tabular/blob/0544fba3c173c5d2bf5153ef189243ff6e0a186f/pytorch_tabular/models/ft_transformer/ft_transformer.py#L173
resulting in an error.

ft_transformer can't be used for datasets that don't have categorical columns?

**Comment by manujosephv** [comment]
Yes. It is an error in the code. It is already fixed on the main branch. Can you check if that works for you? I'll push a release with all these bug fixes bundled to pypi soon.

**Comment by GillianGrayson** [comment]
Everything is fine in the main branch. Looking forward to the new release! Thank you for the best rep for tabular data!
