### ISSUE TITLE
permission denied, running on shared qtree

### ISSUE THREAD

**Issue by ashuarsh** [manujosephv/pytorch_tabular#88]
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Input In [18], in <cell line: 21>()
     12 optimizer_config = OptimizerConfig()
     14 model_config = CategoryEmbeddingModelConfig(
     15     task="classification",
     16     layers="1024-512-512",  # Number of nodes in each layer
     17     activation="LeakyReLU", # Activation between each layers
     18     learning_rate = 1e-3
     19 )
---> 21 tabular_model = TabularModel(
     22     data_config=data_config,
     23     model_config=model_config,
     24     optimizer_config=optimizer_config,
     25     trainer_config=trainer_config,
     26 )

File /cheap/wqforecasttrd/venvs/pt/lib/python3.9/site-packages/pytorch_tabular/tabular_model.py:74, in TabularModel.__init__(self, config, data_config, model_config, optimizer_config, trainer_config, experiment_config, model_callable)
     50 """The core model which orchestrates everything from initializing the datamodule, the model, trainer, etc.
     51 
     52 Args:
   (...)
     71         Typically used when providing Custom Models
     72 """
     73 super().__init__()
---> 74 self.exp_manager = ExperimentRunManager()
     75 if config is None:
     76     assert (
     77         (data_config is not None)
     78         or (model_config is not None)
     79         or (optimizer_config is not None)
     80         or (trainer_config is not None)
     81     ), "If `config` is None, `data_config`, `model_config`, `trainer_config`, and `optimizer_config` cannot be None"

File /cheap/wqforecasttrd/venvs/pt/lib/python3.9/site-packages/pytorch_tabular/config/config.py:497, in ExperimentRunManager.__init__(self, exp_version_manager)
    495 else:
    496     self.exp_version_manager = OmegaConf.create({})
--> 497     os.makedirs(os.path.split(exp_version_manager)[0], exist_ok=True)
    498     with open(self._exp_version_manager, "w") as file:
    499         OmegaConf.save(config=self.exp_version_manager, f=file)

File /nix/store/zi2q1hlbn9fcs7x3dfjhafl3v85f6nw4-python3-3.9.12/lib/python3.9/os.py:225, in makedirs(name, mode, exist_ok)
    223         return
    224 try:
--> 225     mkdir(name, mode)
    226 except OSError:
    227     # Cannot rely on checking for EEXIST, since the operating system
    228     # could give priority to other errors like EACCES or EROFS
    229     if not exist_ok or not path.isdir(name):

PermissionError: [Errno 13] Permission denied: '.pt_tmp'

**Comment by manujosephv** [comment]
@ashuarsh PyTorch Tabular creates a temp directory for storing some files and that directory, by default is `.pt_tmp`. So I'm assuming you are running this on a machine on which you might not have permission to create that folder. In `ExperimentConfig` there is a parameter `_exp_version_manager` which lets you set the location of this temporary file. If you change the folder location to somewhere you do have permission to create a file, it should resolve the issue

**Comment by manujosephv** [comment]
Closing the issue because of inactivity
