### ISSUE TITLE
How to treat null values

### ISSUE THREAD

**Issue by yosen-king** [manujosephv/pytorch_tabular#89]
Node model does not allow null values for training data, and I don't see any solutions about process the null values.
My first idea is that treating it as categorical variables.

**Comment by manujosephv** [comment]
Handling null values is out of scope for the project as dealing with them is very subjective. Just like scikit-learn, this library also expects the users to handle missing values before using the library.

There are a lot of [resources ](https://www.google.com/search?q=handling+missing+values+in+python&sxsrf=ALiCzsbxccAYyW4QQ1xC6iQeQD0xrfsSOQ%3A1660443656919&ei=CFz4Ys7YN-uIz7sPreGtiAk&oq=handle+missing+values&gs_lcp=Cgdnd3Mtd2l6EAEYADIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQsAMQQ0oECEEYAEoECEYYAFAAWABg4RZoAXABeACAAQCIAQCSAQCYAQDIAQnAAQE&sclient=gws-wiz)in the internet to help dealing with missing values.
