### ISSUE TITLE
1. how to return the model structure? something like print(model) in pytorch. 2. when I use the NodeConfig (Modemodel) to train a 2 layers, each layer 512 trees model, it is really really slow, the predcited target remain very the same after one epoch training.

### ISSUE THREAD

**Issue by jzsbioinfo** [manujosephv/pytorch_tabular#9]
- 1. how to return the model structure? something like print(model) in pytorch. 
- 2. when I use the NodeConfig (Modemodel) to train a 2 layers, each layer 512 trees model, it is really really slow, the predcited target remain very the same after one epoch training.

**Comment by manujosephv** [comment]
1. The pure PyTorch model can be accessed using `tabular_model.model`. And even if you are not printing it out explicitly, while training, the model is printed along with the number of parameters.
2. This is little bit a model limitation. NODE is a very heavy model and to get decent enough results, you will have to run for sometime. For NODE I'm basically using the same [implementation ](https://github.com/Qwicen/node)that the original paper authors, just refactored.  What I have noticed is that it requires at least 1024 trees with depth 5 or 6 across all layers to perform well, and that too we need to train for a few more than 1 epoch.  Reducing the number of layers, or the tree depth increase the speed significantly. but also degrades the performance of the model.

**Comment by jzsbioinfo** [comment]
thanks a lot, I will try with the 1024 trees and depth of 5 (although it really takes time to reach the same performance as LGBM using the same dataset). 
Here I also have another question, until now, there are three published model structure avaliable, CategoryEmbeddingModel(for classification), NODEModel and TabNetModel right?  Have compare these model, of their performance, time consuming etc. ?

**Comment by manujosephv** [comment]
There are 4 models as of today
1. CategoryEmbeddingModel(R and C)
2. TabNet (R and C)
3. NODE (R and C)
4. AutoInt (R and C)
5. MixtureDensity Model (Probabilistic Regression only)

But don't have any notebook which compares all of them yet. Feel free to contribute. I think it would be a great addition to examples/tutorials.

**Comment by manujosephv** [comment]
Closing this issue. have opened a new one #17  for the documentation request
