### ISSUE TITLE
Unexpected keyword argument 'checkpoint_callback'

### ISSUE THREAD

**Issue by NicoPiel** [manujosephv/pytorch_tabular#93]
**Describe the bug**
Trying to train a model throws an error.
`TypeError: __init__() got an unexpected keyword argument 'checkpoint_callback'`

**Screenshots**
My code:

```
# train.py
def main(hparams):
    wandb.finish()
    sampler = get_balanced_sampler(df['type'].values.ravel())

    data_config = DataConfig(
        target=['type'], #target should always be a list. Multi-targets are only supported for regression. Multi-Task Classification is not implemented
        continuous_cols=cont_columns,
        categorical_cols=cat_columns
    )

    trainer_config = TrainerConfig(
        auto_lr_find=True, # Runs the LRFinder to automatically derive a learning rate
        batch_size=1024,
        max_epochs=10,
        gpus=1, #index of the GPU to use. -1 means all available GPUs, None, means CPU
    )

    optimizer_config = OptimizerConfig()

    model_config = TabNetModelConfig(
        task="classification",
    )

    experiment_config = ExperimentConfig(

        project_name='bachelor',
        exp_watch='gradients',
        log_target='wandb',
        log_logits=True
    )

    tabular_model = TabularModel(
        data_config=data_config,
        model_config=model_config,
        optimizer_config=optimizer_config,
        trainer_config=trainer_config,
        experiment_config=experiment_config
    )

    tabular_model.fit(train=train, validation=val, train_sampler=sampler)
    result = tabular_model.evaluate(test)

    print(result)

    pred_df = tabular_model.predict(test)
    pred_df.head()

    print_metrics(test['type'], pred_df["prediction"], tag="Holdout")
```

![image](https://user-images.githubusercontent.com/16973767/191124133-81ee0936-1da4-4698-9d0d-7b200ce8b551.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version: v1.43.93; Chromium: 105.0.5195.127 (Official Build) (64-bit)

**Additional context**
You'll find my environment attached.
[environment.txt](https://github.com/manujosephv/pytorch_tabular/files/9602515/environment.txt)

**Comment by JulianRein** [comment]
I had the same error with a too recent pytorch-lightning version. Had 1.7.7 and current pytorch-tabular package installs 1.3.6.
-> downgrade of TIL also required me to downgrade torchmetrics to 0.4.1 (newer might work, but 0.9 did not)

**Comment by manujosephv** [comment]
Should be working in v1.0.*. Have upgraded PyTorch Lightning and torchmetrics. Pls reopen if not
